# Numpy

Biblioteca de processamento matemático de matrizes e arryas. É mais rápido que as listas comuns e têm várias facilidades como sobrecargas de operadores


In [17]:
from IPython.display import display
import numpy as np
import pandas as pd

a1 = np.array([1.0,2.0,3.0])
a2 = np.array([[4,5,6],[7,8,9]])

display(a1,a2)
display(a1.shape, a2.shape) # dimensoes
display(a1.ndim, a2.ndim) # número de dimensões
display(a1.dtype, a2.dtype) #tipo dos dados
display(a1.size, a2.size) # quantidade de elementos

array([1., 2., 3.])

array([[4, 5, 6],
       [7, 8, 9]])

(3,)

(2, 3)

1

2

dtype('float64')

dtype('int64')

3

6

In [18]:
df = pd.DataFrame(a2)
df

0  1  2
0  4  5  6
1  7  8  9

## Criando arrays

Há várias funções de criação de matrizes (cheias de 0 ou de 1, identidade ...)

In [36]:
ones = np.ones(3) # unidimensional
display(ones)

ones = np.ones(shape=(3,3))  # np.ones((3,3))
display(ones)

range_arr = np.arange(-10,10,2)
display(range_arr)

rand_arr = np.random.randint(0,10, size=(3,5))
display(rand_arr)

array([1., 1., 1.])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

array([-10,  -8,  -6,  -4,  -2,   0,   2,   4,   6,   8])

array([[3, 9, 9, 3, 0],
       [4, 5, 1, 1, 6],
       [2, 4, 3, 2, 1]])